
version: '3.8'

services:
  audio-downloader:
    build:
      context: .
      dockerfile: Dockerfile
    image: audio-downloader:latest
    container_name: audio-downloader
    ports:
      - "3000:8080"  # Map to the correct port
    volumes:
      - downloads:/app/downloads
      - audio:/audio
      - playlists:/playlists
      - youtube:/youtube
    environment:
      - NODE_ENV=production
      - OUTPUT_DIR=/audio
      - YOUTUBE_DIR=/youtube
      - THUMBNAILS_ENABLED=true
      - PLAYLIST_DIR=/playlists
      - SAVE_PLAYLISTS_WITH_AUDIO=true  # Flag to save playlists in the same folder as audio
    restart: unless-stopped

volumes:
  downloads:
    driver: local
  audio:
    driver: local
  playlists:
    driver: local
  youtube:
    driver: local

networks:
  default:
    driver: bridge

